class Config():
    def __init__(self):
        self.dc_token = ""
        self.search_fix = ' "Auto-generated by YouTube."'
        self.embed_color = 0xfffffe

        # Event-MSG
        self.on_ready_msg = "BOT IS READY"

config = Config()