class Config():
    def __init__(self):
        self.dc_token = ""
        self.search_fix = ' "Auto-generated by YouTube."'
        
        self.embed_color = {
            "play":0xfffffe,
            "queue":0x72a1ed,
            "queue":0x72a1ed,
            "skip":0x72a1ed
        }

        # Event-MSG
        self.on_ready_msg = "BOT IS READY"

config = Config()